@extends('layouts.admin.app')
@section('title','Ficha técnica')
@section('content')
<div class="content container-fluid"><div class="page-header"><h1 class="page-header-title">{{ $item->name }}</h1></div>
@php($p=$item->costProfile?->calculated_prices ?? [])
<div class="row g-3 mb-4"><div class="col-md-3"><div class="card card-body"><h6>CMV Total</h6><h3>{{ $p['cmv_total'] ?? 0 }}</h3></div></div><div class="col-md-3"><div class="card card-body"><h6>CMV %</h6><h3>{{ $p['cmv_percent'] ?? 0 }}%</h3></div></div><div class="col-md-3"><div class="card card-body"><h6>Preço balcão</h6><h3>{{ $p['counter_price'] ?? $item->price }}</h3></div></div><div class="col-md-3"><div class="card card-body"><h6>Lucro</h6><h3>{{ $p['profit'] ?? 0 }}</h3></div></div></div>
<div class="card mb-4"><div class="card-header"><h4>Adicionar ingrediente do estoque</h4></div><div class="card-body"><form method="post" action="{{ route('admin.costing.ingredient.store',$item) }}" class="row g-2">@csrf <div class="col-md-4"><select name="ingredient_id" class="form-control" required>@foreach($ingredients as $ingredient)<option value="{{ $ingredient->id }}">{{ $ingredient->name }} - {{ $ingredient->unit }}</option>@endforeach</select></div><div class="col"><input name="quantity" type="number" step="0.0001" class="form-control" placeholder="Qtd" required></div><div class="col"><input name="unit" class="form-control" placeholder="g/ml/un" required></div><div class="col"><input name="loss_percent" type="number" step="0.0001" class="form-control" placeholder="Perda %"></div><div class="col"><input name="yield_percent" type="number" step="0.0001" class="form-control" placeholder="Rendimento %"></div><div class="col"><button class="btn btn-primary">Salvar</button></div></form></div></div>
<div class="card"><div class="table-responsive"><table class="table"><thead><tr><th>Ingrediente</th><th>Qtd</th><th>Preço atual</th><th>Preço médio</th><th>Unitário</th><th>Perda</th><th>Rendimento</th><th>Custo</th></tr></thead><tbody>@foreach($item->technicalSheetIngredients as $line)<tr><td>{{ $line->ingredient->name }}</td><td>{{ $line->quantity }} {{ $line->unit }}</td><td>{{ $line->ingredient->current_price }}</td><td>{{ $line->ingredient->average_price }}</td><td>{{ $line->unit_cost_snapshot }}</td><td>{{ $line->loss_percent }}%</td><td>{{ $line->yield_percent }}%</td><td>{{ $line->total_cost }}</td></tr>@endforeach</tbody></table></div></div>
</div>
@endsection
